# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PDF Letterhead Lite' do
  pod 'YAPDFKit', :git => 'https://github.com/mipmip/YAPDFKit.git'
  #pod 'YAPDFKit', :path => '/Users/pim/RnD/Pods/YAPDFKit'

  pod 'MMGetAppStorePrice', :git => 'https://github.com/mipmip/MMGetAppStorePrice.git'
end

target 'PDF Letterhead Pro' do
  pod 'YAPDFKit', :git => 'https://github.com/mipmip/YAPDFKit.git'
  #pod 'YAPDFKit', :path => '/Users/pim/RnD/Pods/YAPDFKit'
end
